### ISSUE TITLE
Support the new 8.0 validation attributes

### ISSUE THREAD

**Issue by roji** [efcore/EFCore.CheckConstraints#103]
https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#data-validation

https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-2/#system-componentmodel-dataannotations-extensions

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/efcore/issues/30754, which should result in a min length constraint.

**Comment by bricelam** [comment]
New attributes:

- AllowedValues
- Base64String
- DeniedValues
- Length

New properties on `Range`:

- MaximumIsExclusive
- MinimumIsExclusive

New properties on `Required`:

- DisallowAllDefaultValues

**Comment by roji** [comment]
Implemented these, with the exception of [Base64String] which is complex (and probably not very useful for databases), opened #138 to track.
