### ISSUE TITLE
The regular expression generated by URLAttribute is insufficient

### ISSUE THREAD

**Issue by aijkl** [efcore/EFCore.CheckConstraints#104]
The regexp implied by the naming of the URLAttribute is a complete check of the URL
The current regular expression is ^(http://|https://|ftp://), which only determines the protocol type, and cannot validate a wrong http url such as "http://hogehoge".

Can I work on this correction?
I would like to make a revision and make a PR, please review.

**Comment by roji** [comment]
@aijkl sorry it took me so long to answer this.

The regular expression generated by this plugin mimics the actual behavior of the .NET [`[Url]`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/UrlAttribute.cs#L18) attribute, which is to test exactly for those three protocols - [here's the source code for that](https://github.com/dotnet/runtime/blob/main/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/UrlAttribute.cs#L18). You can open an issue in the .NET runtime to possibly evolve how that attribute is validated - at that point we can also align the regular expression here (though I very much doubt any proposal here would be accepted - at the very least it would be a breaking change).

Remember that this plugin doesn't do anything you can't do yourself - you can easily specify arbitrary regular expressions in check constraints directly.

> cannot validate a wrong http url such as "http://hogehoge/".

I'm not sure what's wong with that URL - it seems fine to me...
