### ISSUE TITLE
[Request] Implement Required attribute to disallow empty strings

### ISSUE THREAD

**Issue by fbedogni** [efcore/EFCore.CheckConstraints#108]
The required attribute has a property that let's you choose if empty strings are allowed or not
![image](https://github.com/efcore/EFCore.CheckConstraints/assets/46349271/bcaa021b-0310-4fbf-a80f-75ee1e6277e0)
I suggest that if the property is set to false, a lenght > 0 or lenght >=1 should be generated.
Example about a use case of the required parameter with the AllowEmptyStrings property set to false(which should be the default value):
![image](https://github.com/efcore/EFCore.CheckConstraints/assets/46349271/42c84396-3c71-4e33-a1b5-9ee163a36757)

**Comment by roji** [comment]
Makes sense to me. Are you interested in submitting a PR for this?

/cc @ajcvickers

**Comment by fbedogni** [comment]
Yes, i'll gladly try to make the changes for this.
Thank you!
