### ISSUE TITLE
Initial SQL Server setup does not work

### ISSUE THREAD

**Issue by mariusz96** [efcore/EFCore.CheckConstraints#118]
Hi,

As implied in the readme I did [initial setup for SQL Server](https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/tsql-regular-expression-workbench/#third) and now this statement works:
```sql
SELECT dbo.RegexMatch('\b(\w+)\s+\1\b','this has has been repeated')
```
```
1
```
however migration script throws at this line:
```sql
CONSTRAINT [CK_Blogs_Address_Url] CHECK (dbo.RegexMatch('^(http://|https://|ftp://)', [Address])),
```
```
Msg 4145, Level 15, State 1, Line 25
An expression of non-boolean type specified in a context where a condition is expected, near ')'.
```
It appears that the problem is that the CHECK constraint expects a boolean condition but the dbo.RegexMatch function from the red-gate article returns an integer.

Could the correct sql setup script be included somewhere in the readme? Or is it something else that may cause this error?

My (non-working) setup:
```sql
-- https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/tsql-regular-expression-workbench/#third
IF OBJECT_ID (N'dbo.RegexMatch') IS NOT NULL
   DROP FUNCTION dbo.RegexMatch
GO
    
CREATE FUNCTION dbo.RegexMatch
    (
      @pattern VARCHAR(2000),
      @matchstring VARCHAR(MAX)--Varchar(8000) got SQL Server 2000
    )
RETURNS INT
AS BEGIN
    DECLARE @objRegexExp INT,
        @objErrorObject INT,
        @strErrorMessage VARCHAR(255),
        @hr INT,
        @match BIT
    
    
    SELECT  @strErrorMessage = 'creating a regex object'
    EXEC @hr= sp_OACreate 'VBScript.RegExp', @objRegexExp OUT
    IF @hr = 0
        EXEC @hr= sp_OASetProperty @objRegexExp, 'Pattern', @pattern
        --Specifying a case-insensitive match
    IF @hr = 0
        EXEC @hr= sp_OASetProperty @objRegexExp, 'IgnoreCase', 1
        --Doing a Test'
    IF @hr = 0
        EXEC @hr= sp_OAMethod @objRegexExp, 'Test', @match OUT, @matchstring
    IF @hr <> 0
        BEGIN
            RETURN NULL
        END
    EXEC sp_OADestroy @objRegexExp
    RETURN @match
   END
GO
```
```
Commands completed successfully.
```
```sql
-- permissions
sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
sp_configure 'Ole Automation Procedures', 1;
GO
RECONFIGURE;
GO
```
```
Configuration option 'show advanced options' changed from 1 to 1. Run the RECONFIGURE statement to install.
Configuration option 'Ole Automation Procedures' changed from 1 to 1. Run the RECONFIGURE statement to install.
```
```sql
SELECT @@VERSION
```
```
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
	Oct 28 2016 18:17:30 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 22621: )
```

**Comment by roji** [comment]
@mariusz96 thanks for flagging this; I'm currently very busy with EF 8.0 and other stuff, so it will take me a while to get around to investigating this.

**Comment by dkimbell13** [comment]
I am just spit balling here, but will the following work? NOTE: I have not tested this at all...

`-- https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/tsql-regular-expression-workbench/#third
IF OBJECT_ID (N'dbo.RegexMatch') IS NOT NULL
   DROP FUNCTION dbo.RegexMatch
GO
    
CREATE FUNCTION dbo.RegexMatch
    (
      @pattern VARCHAR(2000),
      @matchstring VARCHAR(MAX)--Varchar(8000) got SQL Server 2000
    )
RETURNS BIT -- << This may allow the CHECK method to process the return value as a boolean
AS BEGIN
    DECLARE @objRegexExp INT,
        @objErrorObject INT,
        @strErrorMessage VARCHAR(255),
        @hr INT,
        @match BIT
    
    
    SELECT  @strErrorMessage = 'creating a regex object'
    EXEC @hr= sp_OACreate 'VBScript.RegExp', @objRegexExp OUT
    IF @hr = 0
        EXEC @hr= sp_OASetProperty @objRegexExp, 'Pattern', @pattern
        --Specifying a case-insensitive match
    IF @hr = 0
        EXEC @hr= sp_OASetProperty @objRegexExp, 'IgnoreCase', 1
        --Doing a Test'
    IF @hr = 0
        EXEC @hr= sp_OAMethod @objRegexExp, 'Test', @match OUT, @matchstring
    IF @hr <> 0
        BEGIN
            RETURN NULL
        END
    EXEC sp_OADestroy @objRegexExp
    RETURN @match
   END
GO`

**Comment by mariusz96** [comment]
> I am just spit balling here, but will the following work? NOTE: I have not tested this at all...
> 
> `-- https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/tsql-regular-expression-workbench/#third IF OBJECT_ID (N'dbo.RegexMatch') IS NOT NULL DROP FUNCTION dbo.RegexMatch GO
> 
> CREATE FUNCTION dbo.RegexMatch ( @pattern VARCHAR(2000), @matchstring VARCHAR(MAX)--Varchar(8000) got SQL Server 2000 ) RETURNS BIT -- << This may allow the CHECK method to process the return value as a boolean AS BEGIN DECLARE @objRegexExp INT, @objErrorObject INT, @strErrorMessage VARCHAR(255), @HR INT, @match BIT
> 
> ```
> SELECT  @strErrorMessage = 'creating a regex object'
> EXEC @hr= sp_OACreate 'VBScript.RegExp', @objRegexExp OUT
> IF @hr = 0
>     EXEC @hr= sp_OASetProperty @objRegexExp, 'Pattern', @pattern
>     --Specifying a case-insensitive match
> IF @hr = 0
>     EXEC @hr= sp_OASetProperty @objRegexExp, 'IgnoreCase', 1
>     --Doing a Test'
> IF @hr = 0
>     EXEC @hr= sp_OAMethod @objRegexExp, 'Test', @match OUT, @matchstring
> IF @hr <> 0
>     BEGIN
>         RETURN NULL
>     END
> EXEC sp_OADestroy @objRegexExp
> RETURN @match
> ```
> 
> END GO`

To be used in production it needs to be more solid than that - do you have perhaps info about what values these regexp calls can return?

**Comment by roji** [comment]
Just to set expectations, I'm not going to have any time to test and figure out exactly how to make regex work on SQL Server etc... If someone wants to work on this and possibly make a contribution (to the plugin, to the docs), I'll happily take it though.

**Comment by ErikEJ** [comment]
The check constraint must be a boolean expression. 

This works, for example:

```sql
CREATE TABLE Test
(
	Url nvarchar(1000) NOT NULL CONSTRAINT [CK_Test_Url_Url] CHECK (dbo.RegexMatch('^(http://|https://|ftp://)', [Url]) > 0),
)

insert test values ('ftp:/testing')

insert test values ('ftp://testing')
```

https://github.com/efcore/EFCore.CheckConstraints/blob/c966999c64e81e942b59464b88334b501b159d80/EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs#L328

```csharp
SqlServerDatabaseProviderName => "dbo.RegexMatch('{1}', {0}) > 0",
```

**Comment by ErikEJ** [comment]
@roji Let me know what you think, happy to do a PR

**Comment by roji** [comment]
@ErikEJ sure! If that works and the docs need amending, a PR would be great.

**Comment by ErikEJ** [comment]
@roji The docs are fine, it is just a minor implementation change:

`SqlServerDatabaseProviderName => "dbo.RegexMatch('{1}', {0}) > 0",`

**Comment by roji** [comment]
Oh OK - then yeah, absolutely. I can release a 8.0.1 for that.

**Comment by ErikEJ** [comment]
Notice that sp_oacreate is not available with Azure SQL Database. 

A user defined function wrapping an api call seems to be a possible (but slow) alternative.

https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-invoke-external-rest-endpoint-transact-sql?view=azuresqldb-current&tabs=request-headers#a-call-an-azure-function-using-an-http-trigger-binding-without-authentication

**Comment by mariusz96** [comment]
Thanks, @ErikEJ - I compiled master branch locally and it works fine now.
