### ISSUE TITLE
UseEnumCheckConstraints is not working on nullable enum properties.

### ISSUE THREAD

**Issue by qsdfplkj** [efcore/EFCore.CheckConstraints#14]
The UseEnumCheckConstraints  doesn't generate a constraint for nullable enum (both as int or string) properties.

    public class YourEntity
    {
        YourEnum? YourProperty { get ;set ;}
    }

  public enum YourEnum { Value1, Value2 }

**Comment by roji** [comment]
Thanks for flagging this, and sorry it's taken so long to address.
