### ISSUE TITLE
Add additional URL protocols to Common Url pattern

### ISSUE THREAD

**Issue by ErikEJ** [efcore/EFCore.CheckConstraints#147]
sftp:// ftps:// file://

(Happy to create a PR)

**Comment by roji** [comment]
Hey @ErikEJ, the intent here was to mimic exactly the .NET validation behavior of that attribute, which doesn't support those schemes - see https://github.com/efcore/EFCore.CheckConstraints/issues/104#issuecomment-1860704262. What do you think?

**Comment by ErikEJ** [comment]
Makes sense to keep it as is then
