### ISSUE TITLE
.NET 9 support

### ISSUE THREAD

**Issue by ZzZombo** [efcore/EFCore.CheckConstraints#175]

**Comment by roji** [comment]
I'll do this, but it'll take a bit of time - please be patient.

**Comment by ErikEJ** [comment]
Happy to help?

**Comment by roji** [comment]
@ErikEJ sure, feel free! I don't know if there are any open issues that are worth looking into as well as part of this release, if you feel like it take a look!

**Comment by ErikEJ** [comment]
@roji Cool. Only one is Azure regex, but it is still in preview. Would appreciate your eyes on my PR .

**Comment by roji** [comment]
I usually do a NamingConventions/CheckConstraints "phase" at some point after each release quiets down a bit - can you ping me in a few weeks??
