### ISSUE TITLE
May CheckContraints be used without setting up Regular Expressions for SQL Server?

### ISSUE THREAD

**Issue by SetTrend** [efcore/EFCore.CheckConstraints#18]
I'm very keen to use EFCore.CheckConstraints on SQL Server, yet I wouldn't want to use or require Regular Expression constraints on an on-premise SQL Server installation because that would involve additional setup efforts.

Can I disable regular expression check constraints even when `RegularExpressionAttribute` is present in entity property?

**Comment by SetTrend** [comment]
*ping* - Anyone?

**Comment by AndriySvyryd** [comment]
Currently you can only disable all validation attribute check constraints together. Once https://github.com/dotnet/efcore/issues/214 is implemented you can create a type derived from [ValidationCheckConstraintConvention](https://github.com/efcore/EFCore.CheckConstraints/blob/main/EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs) and override `SupportsRegex`

**Comment by SetTrend** [comment]
Ah, very interesting!

In the meantime, I implemented an update to the current version where I added this optional feature, plus full-fledged XML documentation comments. I'm currently using [that version](/SetTrend/EFCore.CheckConstraints) for now.

So, I guess, you wouldn't want to pull my PRs for the time being until /dotnet/efcore/issues/214 gets implemented?
