### ISSUE TITLE
Generate enum check constraints with BETWEEN where the value range is contiguous

### ISSUE THREAD

**Issue by roji** [efcore/EFCore.CheckConstraints#3]
Originally raised by @henrikdahl8240 in https://github.com/dotnet/efcore/issues/20868.

This could have some perf impact (not confirmed), and would make for much tighter SQL, especially for big enums. Could go all-out and detect multiple ranges of values too.

**Comment by henrikdahl8240** [comment]
@roji I would like to kindly suggest you to see the comments put at the issue I filed in the T-SQL forum the other day, i.e. https://social.msdn.microsoft.com/Forums/en-US/f2ed1fc4-aeef-4fdc-b79a-28ff064e71a8/how-is-a-check-constraint-using-the-in-operator-actually-being-processed-for-an-int-column?forum=transactsql

There's some guy, who claims he is an SQL Server MVP, so perhaps we may have confidence in his statement, as he states:

> It would also be different if you have a really long list of values, more than 64. In this case, SQL Server transforms the IN list to an internal temp table, so that could make a noticable difference to BETWEEN.

As you can see, I asked him for the source of information.

The comment added by Joe Celko on various implementations of SQL servers are also very interesing. By the way I am a great fan of his books.

Isn't it just pretty obvious that using BETWEEN is trivially favorable, at least as you have only one contigous range and at least one item in the range? If SQL Server actually implements a binary search tree as CELKO writes in case of DB2, it would not make much benefit in case of multiple contigous ranges to enurate a number of OR'ed BETWEENS.

**Comment by roji** [comment]
Thanks for the additional info. I personally prefer to simply measure rather than to read what people write - implementations may change with time, and it's possible that since this was written SQL Server does actually detect contiguous IN ranges and optimize them (though I doubt it). It would just be a matter of a quick benchmark.

But in any case, I agree this is a good idea. There's no actual downsides to doing this, even if SQL Server specifically optimized this, others probably don't, and at worse it results in terse SQL. On the other hand, I probably won't have any time to actually work on it - so if anyone wants to submit a PR that would be great.
