### ISSUE TITLE
enum generation not as stated

### ISSUE THREAD

**Issue by DickBaker** [efcore/EFCore.CheckConstraints#44]
seems that today's (8 Sept) EF Community Standup produced "CHECK ([OrderStatus] = 0 OR [OrderStatus] = 1)" and not the "CHECK ([OrderStatus] IN (0, 1))" described in this README.md

**Comment by roji** [comment]
Thanks @DickBaker - once work on EF Core 6.0 stops I'll work on making this extension work with it, and will take a look at this as well. I'm not sure why it produces a set of ORs rather than the more concise IN form.

**Comment by roji** [comment]
Odd, I looked at this again and I'm seeing the `IN (0,1)` - not sure how this happened (we possibly got confused on live TV?). Will close for now and revisit if it pops up again.
