### ISSUE TITLE
Add check constraints for validation attributes

### ISSUE THREAD

**Issue by bricelam** [efcore/EFCore.CheckConstraints#5]
Attribute | Expression
--- | ---
[Compare("Y")] | X == Y
[MinLength(8)] | X.Length >= 8
[Range(0, 10)] | X >= 0 && X <= 10
[RegularExpression("[0-9A-F]+") | Regexp.IsMatch(X, "[0-9A-F]+")
[DataType(...)] | (predefined regular expressions)

Originally https://github.com/dotnet/efcore/issues/15410

**Comment by roji** [comment]
@bricelam as discussed, the complication here is that most SQL expressions here are provider-dependent, but this is a general plugin. Ideally EF would allow defining check constraints (and default and computed column expressions) via a LINQ expression, translated by the query pipeline.

But a dirty idea... Until that's done, we can hack support in the plugin for several well-known providers, hard-coding the SQL for each one :) What do you think?

**Comment by bricelam** [comment]
I'd just mark it as blocked on https://github.com/dotnet/efcore/issues/15409 and wait for feedback before looking for ways to do it sooner.

**Comment by roji** [comment]
Too late, it's already mostly done :sweat_smile:
