### ISSUE TITLE
Discriminator check constraint contains values for abstract classes

### ISSUE THREAD

**Issue by sandord** [efcore/EFCore.CheckConstraints#54]
I have a class hierarchy with an abstract `ProductBase` class and two concrete classes inheriting from it: `ProductType1` and `ProductType2`.

The following (Postgres) DDL is generated for the `products` table:

    discriminator text not null
        constraint "CK_products_Discriminator"
          check (discriminator = ANY
                 (ARRAY ['ProductBase'::text, 'ProductType1'::text, 'ProductType2'::text]))

As you can see, a discriminator value for the abstract base class `ProductBase` is included in the list while that discriminator value should never be in the table since the class is abstract.

Unless there is a special case I'm missing, I think only discriminators for concrete types should be added to the `CHECK` constraint.

**Comment by roji** [comment]
Makes sense - thanks. Are you interested in submitting a PR for this?

**Comment by sandord** [comment]
Great! I was looking for time to submit a PR but seeing that it already has been fixed is perfect.
