### ISSUE TITLE
Range check doesn't work for decimals

### ISSUE THREAD

**Issue by sandord** [efcore/EFCore.CheckConstraints#55]
I've got a few properties of the type `decimal` on my entities and they have a `RangeAttribute` declared on them.

I don't see any `CHECK` constraints in my migrations though.

I suspect this is due to this check: 

https://github.com/efcore/EFCore.CheckConstraints/blob/db27cbe7850214347a7d231332d4c4d92155f067/EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs#L100

I understand the rationale behind it but `decimal` is kind of a special case, since it is not a primitive (CLR) type but a struct instead. There is no constructor overload on the `RangeAttribute` for `decimal` because attribute declarations can only have constant values (this is a CLR limitation) and since `decimal` is not a primitive type, it can not be expressed as a constant in an attribute constructor. 

This is why I declare `RangeAttribute` on `decimal` properties with `float` or `double` constants passed into the attribute as a workaround.

Perhaps the check could be extended with the following: if the range value type mismatches the mapped type but the range values can be converted back and forth to the mapped type successfully, the check constaint can be rendered after all. The idea is that this proves that no precision is lost in the conversion.

I believe this will cover most cases since often you'd want to limit the range to positive values or between 0 and 1 etc.

**Comment by roji** [comment]
> I understand the rationale behind it but decimal is kind of a special case, since it is not a primitive (CLR) type but a struct instead. There is no constructor overload on the RangeAttribute for decimal because attribute declarations can only have constant values (this is a CLR limitation) and since decimal is not a primitive type, it can not be expressed as a constant in an attribute constructor.

AFAIK decimal is a primitive just like int, and there's no problem with passing a decimal literal in an attribute:

```c#
[SomeAttribute(1.3m)]
```

It just so happens that RangeAttribute supports int and double, but not range - probably without any good reason.

> This is why I declare RangeAttribute on decimal properties with float or double constants passed into the attribute as a workaround.

I'm not sure this would be appropriate. Float/double and decimal are very different types - I think it's better to keep things very simple and explicit here. Other types are also missing from RangeAttribute (e.g. short); I'm also assuming other vaildation frameworks wouldn't respect this, so we'd end up with an attribute scenario that works on EF Core but not elsewhere...

Note that it's really trivial to just manually define a check constraint yourself, without going through RangeAttribute.

**Comment by sandord** [comment]
> AFAIK decimal is a primitive just like int, and there's no problem with passing a decimal literal in an attribute:

Decimal is not a primitive, which can be proven by this statement: 

    > typeof(decimal).IsPrimitive
    false

Regarding attribute parameter types, `decimal` is not allowed per the spec: https://github.com/dotnet/csharplang/blob/main/spec/attributes.md#attribute-parameter-types

I have to admit I was a little surprised when I first read about it but there it is.

I agree that my workaround wouldn't be very appropriate in a general sense. I'm aware that fixed point and floating point numbers are very different conceptually and can't be generally be converted vice versa in a safe manner. Even only allowing value conversion for which the conversion can be proven to be safe, it would probably be confusing to developers.

**Comment by sandord** [comment]
By the way, I mistakenly stated that the `decimal` type was a `struct` as *opposed* to primitive types. But many of the primitive types are actually structs, such as `int` and `float`.

**Comment by roji** [comment]
You're right about IsPrimitive, though the fact that decimal has a special literal format in the language shows it is not just any type (I guess I'm not sure exactly what C# defines as a primitive). You're also right about passing decimal to an attribute, though since it has a literal form (`1m`) it can be passed to an attribute as an object. So RangeAttribute could very well have supported decimal had that been a goal.

>  I'm aware that fixed point and floating point numbers are very different conceptually and can't be generally be converted vice versa in a safe manner.

decimal isn't a fixed point number - it's a floating point number, only decimal.

In any case, thanks for the conversation - it's an interesting idea, just not something I think a general-purpose plugin like this should support... I'll go ahead and close this issue, though feel free to post back and continue the conversation.
