### ISSUE TITLE
InvalidOperationException with in-memory DB

### ISSUE THREAD

**Issue by angularsen** [efcore/EFCore.CheckConstraints#63]
Trying to use the DB context in an integration test fails on initialization with `System.InvalidOperationException`: `Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMappingSource' while attempting to activate 'EFCore.CheckConstraints.Internal.CheckConstraintsConventionSetPlugin'.`

### Root cause
`IRelationalTypeMappingSource` is not configured by `Microsoft.Extensions.DependencyInjection.InMemoryServiceCollectionExtensions.AddEntityFrameworkInMemoryDatabase`

It is configured by `Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer` and other EF Core providers like this:

```cs
            new EntityFrameworkRelationalServicesBuilder(serviceCollection)
                .TryAdd<IRelationalTypeMappingSource, SqlServerTypeMappingSource>()
```

### Setup
```cs
public class MyAppDbContext : DbContext 
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseEnumCheckConstraints();
    }
}

// MyWebApplicationFactory for integration tests
public class MyWebApplicationFactory : WebApplicationFactory<Startup>
{
    protected override void ConfigureTestServices(IServiceCollection s)
    {
        s.AddDbContext<MyAppDbContext>((_, opt) => opt.UseInMemoryDatabase("InMemory"));
    }
}
```

### Workaround
Do not configure EFCore.CheckConstraints in tests.

### Solution
Not sure, but it would be helpful if this plugin "just worked" with in-memory DB, even if it is not actually used for anything. This helps write integration tests without having to add workarounds. 

Can this plugin maybe take a dependency on `IServiceProvider` and manually try to resolve the dependencies, and log a warning if not found?

**Comment by roji** [comment]
@angularsen this plugin can only work with relational providers - it requires relational features and cannot work on InMemory. Just like you're configuring InMemory as your provider in your tests, you should refrain from adding this plugin.

**Comment by angularsen** [comment]
@roji Thank you for the quick reply. I have yet to find a good way to override DbContext.OnConfiguring from my integration test in order to not include this plugin, do you have any tips?

**Comment by roji** [comment]
How are you managing to configure InMemory in your tests as opposed to your real provider otherwise? The same should work for deciding whether to use the plugin, no?

**Comment by angularsen** [comment]
It is pretty much like this:

Startup
```cs
services.AddDbContext<MyAppDbContext>((serviceProvider, options) =>
{
    options.UseSqlServer(myConnectionString, builder =>
    {
        // configure SQL server provider
    });
});
```

Integration test overriding services in `WebApplicationFactory.ConfigureTestServices()`
```cs
services.AddDbContext<MyAppDbContext>((serviceProvider, opt) => opt.UseInMemoryDatabase("InMemory"));
```

Since the plugin is configured inside `MyAppDbContext.OnConfiguring()`, I can't see how I can easily manipulate the `MyAppDbContext` instance to not add the plugin for integration tests. The best I can think of is injecting `IHostEnvironment` or an `IOptions<>` into its constructor to control this from configuration.

**Comment by roji** [comment]
Why not move the plugin configuration to AddDbContext?

```c#
services.AddDbContext<MyAppDbContext>((serviceProvider, options) => options
    .UseSqlServer(myConnectionString, builder =>
    {
        // configure SQL server provider
    })
    .UseAllCheckConstraints());
```

**Comment by angularsen** [comment]
Ah, I didn't realize the same configuration could be applied there. That is perfect, thanks!
