### ISSUE TITLE
feat: Add Constraint for brazilian official info

### ISSUE THREAD

**Issue by VictorLlanir** [efcore/EFCore.CheckConstraints#79]
## What should be done?
It would be nice to have validations for some official data, like CPF, CPNJ etc..

I willl work on this two first validations  - CPF and CNPJ.

**Comment by roji** [comment]
@VictorLlanir this plugin isn't meant to include any arbitrary check constraints for specific applications, but rather ones that make sense in general for .NET/EF users (e.g. enums, discriminators...). Note that anyone can define any check constraints they want in their application via the EF API ([see docs](https://docs.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#check-constraints)). If you think your check constraint are generally useful and would like to make them easily accessible for users, you can easily create another plugin specifically for Brazilian info (you're welcome to copy this plugin as a basis).

**Comment by VictorLlanir** [comment]
@roji, thanks for your explanation, you're right. It would be better for me to create an extension of this project.
Thanks, I'm closing this issue!
